global:
  flushLogSize: 1MB
  logAPIEndPoint: https://log-api.newrelic.com/log/v1
  logLevel: info

conversationLogs:
  enabled: True
  pollingInterval: 5m

channelDetails:
  enabled: True
  pollingInterval: 6h

userLogs:
  enabled: True
  pollingInterval: 24m

accessLogs:
  enabled: True
  pollingInterval: 5m

auditLogs:
  enabled: True
  pollingInterval: 5m
